// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy1h125bDvKo4cs13Lc7RxSXeNjvx_YrI',
    appId: '1:186654276393:web:d455aaa263cae33a6f5538',
    messagingSenderId: '186654276393',
    projectId: 'ctrlplay-37a48',
    authDomain: 'ctrlplay-37a48.firebaseapp.com',
    storageBucket: 'ctrlplay-37a48.firebasestorage.app',
    measurementId: 'G-BWW4DDYVWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7_B22aNzbPY5S49HAc0ekaEeWzkjc8M',
    appId: '1:186654276393:android:340f80985c3b4f016f5538',
    messagingSenderId: '186654276393',
    projectId: 'ctrlplay-37a48',
    storageBucket: 'ctrlplay-37a48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_b_rwMLgCoqFIlcyQWjMqq7wgUQNIZjM',
    appId: '1:186654276393:ios:d741abfffbc7fdf46f5538',
    messagingSenderId: '186654276393',
    projectId: 'ctrlplay-37a48',
    storageBucket: 'ctrlplay-37a48.firebasestorage.app',
    iosBundleId: 'cl.jmunoz.ctrlplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_b_rwMLgCoqFIlcyQWjMqq7wgUQNIZjM',
    appId: '1:186654276393:ios:3011a4a1626930826f5538',
    messagingSenderId: '186654276393',
    projectId: 'ctrlplay-37a48',
    storageBucket: 'ctrlplay-37a48.firebasestorage.app',
    iosBundleId: 'com.example.ctrplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy1h125bDvKo4cs13Lc7RxSXeNjvx_YrI',
    appId: '1:186654276393:web:fc8abd340abc0dcf6f5538',
    messagingSenderId: '186654276393',
    projectId: 'ctrlplay-37a48',
    authDomain: 'ctrlplay-37a48.firebaseapp.com',
    storageBucket: 'ctrlplay-37a48.firebasestorage.app',
    measurementId: 'G-CGBP2LESS8',
  );
}
